env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse

  - name: LATEST_TABLE
    valueFrom: latest-table

  - name: TRADES_TABLE
    valueFrom: trades-table

  - name: GOLD_1M_TABLE
    valueFrom: gold-1m

  - name: STREAMLIT_GATHER_USAGE_STATS
    value: 'false'